##############################################
# Eternal Prism
# Живое небо, аврора, прозрачная вода, тени
# Minecraft 1.21.11 / Iris
##############################################

profile.eternal_prism.name=Eternal Prism

# Нужны дополнительные буферы для SSAO и god rays
colortex1.format=RGBA16
colortex2.format=RGB16
